# Theme
theme: alembic-jekyll-theme
# Google Analytics
google_analytics: UA-114243378-3
# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
